.version
.database
.show
.tables


-- TABLA PARA USUARIOS

CREATE TABLE JA_USUARIOS
(
    IdUsuarios      INTEGER PRIMARY KEY AUTOINCREMENT,
    NombreUsuario   VARCHAR(30) UNIQUE NOT NULL,
    PasswordUsuario VARCHAR(30) NOT NULL,
    FechaCreacion   DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM JA_USUARIOS

--CODIGO CREACION TABLAS
CREATE TABLE JA_HORARIO
(
    IdHorario   INTEGER PRIMARY KEY AUTOINCREMENT,
    DiaHorario  VARCHAR(20) not NULL,
    HoraHorario VARCHAR(10) NOT NULL
    
);

CREATE TABLE JA_TIPO_ARSENAL
(
    IdTipoArsenal       INTEGER PRIMARY KEY AUTOINCREMENT,
    NombreTipoArsenal   VARCHAR(30) NOT NULL
);

CREATE TABLE JA_COORDENADAS
(
    IdCoordenada       INTEGER PRIMARY KEY AUTOINCREMENT,
    NombreCoordenada   VARCHAR(30) NOT NULL
);


SELECT * FROM JA_HORARIO
SELECT * FROM JA_TIPO_ARSENAL
SELECT * FROM JA_COORDENADAS


DROP TABLE JA_HORARIO 
DROP TABLE JA_TIPO_ARSENAL
DROP TABLE JA_COORDENADAS
DROP TABLE JA_USUARIOS





